### PR TITLE
Merge latest fixes

### PR DESCRIPTION
**Pull request by xTVaser**
This wraps the Recording and Lua tools around a config option which can be enabled or disabled from the System menu, the enabling is also gated with a prompt warning that these new additions are experimental, and still a work-in-progress, etc.  

I ended up going with normal ifs using EmuOptions, as `ifdefs` did not make sense to me since that is all pre-processor stage (end-users would not be able to enable the tools); virtual methods and overriding the methods I touch seemed like it would be a huge amount of unnecessary code duplication (re-writing a several hundred line method to add just 1 line for example).  But I'm not a huge C++ guy so I could be completely off-base.

Some refactors throughout to change filenames and make the recording tools less TAS specific.  (mentions of `Key` were improved to `Input` and Movies/TAS changed to `Recording`)

Identified some bugs and problems along the way, fixed those which I deemed blockers for getting this merged, the rest I will make issues and follow up on.

After these changes I will split off the Recording tools from the Lua tools and make a separate PR for both, hopefully that makes reviewing easier.

### CODE REVIEW

**Comment by mirh** [comment]
> I ended up going with normal ifs using EmuOptions, as ifdefs did not make sense to me since that is all pre-processor stage

That would actually be the \*important\* point, I guess, if a dev really wanted to compile the thing 'quickly' or really be sure some whatever bug is not due to it *at all*. 

OTOH, I'm not sure how much really sought-after this use case would be... In particular if one day we'll make cheats depend on it.

**Comment by bositman** [comment]
Good job, I'll grab a build and see if the crash at boot bug is gone (like 50% chance PCSX2 crashes before it reaches booting the game :P )

**Comment by xTVaser** [comment]
@mirh Ahhh true, I guess I was too focused on having 1 solution to accomplish everything.  I'll add the `ifdefs` as well then.  That way it facilitates the developer's use-case if ever needed.  But I think it is good for it to be toggable by the user incase these features are cluttering / do actually impact performance (better to be off by default)

@bositman I don't really use a large library of games with pcsx2, I pretty much only use pcsx2 for `Jak II`.  What games are causing the crashes? I could probably find the problem locally if I knew; I've yet to ever had the emulator crash.

**Comment by bositman** [comment]
All of them :P It seems to be something at init, maybe if you sent me a debug build i could trace it

**Comment by xTVaser** [comment]
Well can you just give me one example title that crashes, like I said the one game I've been testing with works perfectly fine.  Unless I can reproduce it locally I can't really fix it unless it's a very trivial issue.

Debug build here - https://github.com/xTVaser/pcsx2-rr/releases/tag/untagged-64b7118c6a776cf12d18

**Comment by mirh** [comment]
> But I think it is good for it to be toggable by the user incase these features are cluttering / do actually impact performance (better to be off by default)

Absolutely!
Though I just thought you couldn't be bothered with having both /s

**Comment by bositman** [comment]
I've tested over 10 games and they all get the crash. Moreover, it happens before isofileopen, so its somewhere at the bios execution, so should be game independent. 

Debug build made it less frequent but still crashed, here's an example log:
`Loading language translation databases for 'Greek' [el_GR]
	pcsx2_Main not found -- translation dictionary may be incomplete.
	pcsx2_Iconized not found -- translation dictionary may be incomplete.
SetLanguage: Requested translation is not implemented yet.
PCSX2 1.5.0-20180603222913 - compiled on Jun 17 2018
Savestate version: 0x9a0d0000

Host Machine Init:
	Operating System =  Microsoft Windows 7 Ultimate Edition Service Pack 1 (build 7601), 64-bit
	Physical RAM     =  16367 MB
	CPU name         =  Intel(R) Core(TM) i5-2500K CPU @ 3.30GHz
	Vendor/Model     =  GenuineIntel (stepping 07)
	CPU speed        =  3.291 ghz (4 logical threads)
	x86PType         =  Standard OEM
	x86Flags         =  bfebfbff 1f9ae3bf
	x86EFlags        =  28100000

x86 Features Detected:
	SSE2.. SSE3.. SSSE3.. SSE4.1.. SSE4.2.. AVX

Loading language translation databases for 'Greek' [el_GR]
	pcsx2_Main not found -- translation dictionary may be incomplete.
	pcsx2_Iconized not found -- translation dictionary may be incomplete.
SetLanguage: Requested translation is not implemented yet.
Reserving memory for recompilers...

Loading plugins from H:\PCSX2 tests\TAS TEST\plugins...
	Bound   GS: GSdx32-SSE4.dll [GSdx 20180606122006 (MSVC 19.00 SSE4.1/AVX) 1.1.0]
	Bound  PAD: LilyPad.dll [LilyPad (20180606122006) 0.12.1]
	Bound SPU2: Spu2-X.dll [SPU2-X 20180606122006 2.0.0]
	Bound CDVD: cdvdGigaherz.dll [cdvdGigaherz 20180606122006 0.11.0]
	Bound  USB: USBnull.dll [USBnull Driver 20180606122006 0.7.0]
	Bound   FW: FWnull.dll [FWnull Driver 20180606122006 0.7.0]
	Bound DEV9: DEV9null.dll [DEV9null Driver 20180606122006 0.5.0]
Plugins loaded successfully.

(GameDB) 9591 games on record (loaded in 123ms)
Loading language translation databases for 'Greek' [el_GR]
	pcsx2_Main not found -- translation dictionary may be incomplete.
	pcsx2_Iconized not found -- translation dictionary may be incomplete.
SetLanguage: Requested translation is not implemented yet.
HLE Notice: ELF does not have a path.

Initializing plugins...
	Init GS
	Init PAD
	Init SPU2
	Init CDVD
	Init USB
	Init FW
	Init DEV9
Plugins initialized successfully.

Patches: No CRC found, using 00000000 instead.
Opening plugins...
	Opening GS
	Opening PAD
	Opening SPU2
	Opening CDVD
isoFile open ok: E:\zimages\DragonBall Z - Budokai 3 (USA).iso
	Image type  = DVD
 * CDVD Disk Open: DVD, Single layer or unknown:
 * * Track 1: Data (Mode 1) (2274320 sectors)
	Opening USB
	Opening FW
	Opening DEV9
3.x GL context successfully created
OpenGL information. GPU: GeForce GTX 760/PCIe/SSE2. Vendor: NVIDIA Corporation. Driver: NVIDIA 388.31
INFO: GL_EXT_texture_filter_anisotropic is available
INFO: GL_ARB_gpu_shader5 is available
INFO: GL_ARB_viewport_array is available
INFO: GL_ARB_shader_image_load_store is available
INFO: GL_ARB_clear_texture is available
INFO: GL_ARB_direct_state_access is available
INFO: GL_ARB_texture_barrier is available
INFO: GL_ARB_get_texture_sub_image is available

Current Renderer: OpenGL (Hardware renderer)
Available VRAM/RAM:3356MB for textures
GSdx Lookup CRC:0
McdSlot 0 [File]: [is not memcard file]
McdSlot 1 [File]: H:\PCSX2 tests\TAS TEST\memcards\Mcd002.ps2
McdSlot 0: [Folder] H:\PCSX2 tests\TAS TEST\memcards\superfolder.ps2
(FolderMcd) Indexing slot 0 with filter "".
GSdx Lookup CRC:0
Plugins opened successfully.
EE/iR5900-32 Recompiler Reset
	Bios Found: Europe  v01.70(27/02/2003)  Console
	BIOS rom2 module not found, skipping...
	BIOS erom module not found, skipping...
# Initialize memory (rev:3.63, ctm:196Mhz, cpuclk:147Mhz detected)
`

**Pull request merged**
